# Generated by Django 3.2.5 on 2021-07-31 02:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team_yt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('button_text', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='media/services/%Y/%m')),
                ('description', ckeditor.fields.RichTextField()),
                ('created_date', models.CharField(max_length=250)),
            ],
        ),
    ]
