# Generated by Django 3.2.5 on 2021-07-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
