# Generated by Django 3.2.6 on 2021-08-03 12:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_alter_services_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='media/about/%Y/%m/%d')),
            ],
        ),
    ]
