# Generated by Django 3.2.6 on 2021-08-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='fade',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
