# Generated by Django 3.2.5 on 2021-07-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210725_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
