# Generated by Django 3.2.6 on 2021-08-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactInfo', '0002_contactinfo_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact',
            field=models.CharField(max_length=255),
        ),
    ]
