# Generated by Django 3.2.6 on 2021-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactInfo', '0003_auto_20210803_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='add',
            field=models.TextField(blank=True),
        ),
    ]
